DROP TABLE PRET CASCADE CONSTRAINTS;
DROP TABLE ADHERENT CASCADE CONSTRAINTS;
DROP TABLE COLLECTION CASCADE CONSTRAINTS;
DROP TABLE LIVRES CASCADE CONSTRAINTS;
DROP TABLE AUTEUR CASCADE CONSTRAINTS;
DROP TABLE EDITEUR CASCADE CONSTRAINTS;
DROP TABLE CATEGORIE CASCADE CONSTRAINTS; 
