-- primary keys
ALTER TABLE LIVRES ENABLE CONSTRAINT PK_LIVRES;
ALTER TABLE ADHERENT ENABLE CONSTRAINT PK_ADHERENT;
ALTER TABLE COLLECTION ENABLE CONSTRAINT PK_COLLECTION;
ALTER TABLE EDITEUR ENABLE CONSTRAINT PK_EDITEUR_ID#;
ALTER TABLE AUTEUR ENABLE CONSTRAINT PK_AUTEUR_ID#;
ALTER TABLE PRET ENABLE CONSTRAINT PK_PRET;
ALTER TABLE CATEGORIE ENABLE CONSTRAINT PK_CATEGORIE_CAT#;

-- foreign keys
ALTER TABLE LIVRES ENABLE CONSTRAINT FK_IDAUTEUR;
ALTER TABLE LIVRES ENABLE CONSTRAINT FK_IDEDITEUR;
ALTER TABLE LIVRES ENABLE CONSTRAINT FK_IDCOLL;
ALTER TABLE PRET ENABLE CONSTRAINT FK_ADH;
ALTER TABLE PRET ENABLE CONSTRAINT FK_REF_LIVRES;
ALTER TABLE CATEGORIE ENABLE CONSTRAINT FK_CAT_LIVRES;