-- foreign keys
ALTER TABLE LIVRES DISABLE CONSTRAINT FK_IDAUTEUR;
ALTER TABLE LIVRES DISABLE CONSTRAINT FK_IDEDITEUR;
ALTER TABLE LIVRES DISABLE CONSTRAINT FK_IDCOLL;
ALTER TABLE PRET DISABLE CONSTRAINT FK_ADH;
ALTER TABLE PRET DISABLE CONSTRAINT FK_REF_LIVRES;
ALTER TABLE CATEGORIE DISABLE CONSTRAINT FK_CAT_LIVRES;

-- primary keys
ALTER TABLE LIVRES DISABLE CONSTRAINT PK_LIVRES cascade;
ALTER TABLE ADHERENT DISABLE CONSTRAINT PK_ADHERENT cascade;
ALTER TABLE COLLECTION DISABLE CONSTRAINT PK_COLLECTION cascade;
ALTER TABLE EDITEUR DISABLE CONSTRAINT PK_EDITEUR_ID# cascade;
ALTER TABLE AUTEUR DISABLE CONSTRAINT PK_AUTEUR_ID# cascade;
ALTER TABLE PRET DISABLE CONSTRAINT PK_PRET cascade;
ALTER TABLE CATEGORIE DISABLE CONSTRAINT PK_CATEGORIE_CAT# cascade;