LOAD DATA INFILE 'Y:\GitHubs_Repo\projetMopolopolo\data_unique.csv'

INTO TABLE AUTEUR
FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY "'"
(NOM_AUTEUR ,
	PRENOM_AUTEUR,
	DATE_NAISSANCE DATE "DD-MM-YYYY")