SHUTDOWN IMMEDIATE;
set DBID 1461388802;
STARTUP MOUNT;
RECOVER DATABASE DELETE ARCHIVELOG;
RESTORE TABLESPACE DATA_TBS, INDEX_TBS;
RESTORE CONTROLFILE to '\tmp\' from autobackup;
RESTORE SPFILE to '\tmp\' from autobackup;
ALTER DATABASE OPEN RESETLOGS;