CONFIGURE CHANNEL DEVICE TYPE DISK FORMAT '%ORACLE_BASE%\oradata\orcl\backup\full_%u_%s_%p';
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
BACKUP DATABASE;
BACKUP TABLESPACE DATA_TBS, INDEX_TBS;
BACKUP ARCHIVELOG ALL NOT BACKED UP SINCE TIME 'SYSDATE-1';
BACKUP SPFILE;
BACKUP CURRENT CONTROLFILE;
STARTUP;