CONFIGURE CHANNEL DEVICE TYPE DISK FORMAT '%ORACLE_BASE%\oradata\orcl\backup\full_%u_%s_%p';
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
configure controlfile autobackup on;
BACKUP DATABASE plus ARCHIVELOG include current controlfile;
BACKUP TABLESPACE DATA_TBS, INDEX_TBS;
BACKUP SPFILE;
ALTER DATABASE OPEN;